@startuml

' ########## Provider ##########
interface Provider {
    + void provide()
    + void requireIncentive()
}
abstract class AbstractProvider {
    - int ID
    - List<Information> knowHow
    - BigDecimal requiredIncentive
    - BigDecimal earnedIncentive
    - BigDecimal provideProbability
    + void provide()
    + void requireIncentive()
}
class RandomProvider {
    + void provide()
    + void requireIncentive()
}
class Providers {
    + Provider newRandomProvider()
    + void requireIncentive()
}

AbstractProvider ..|> Provider
RandomProvider --|> AbstractProvider
RandomProvider .r.|> Provider
Providers .r.> RandomProvider : <<create>>

AbstractProvider "1" o-- "1..*" KnowHow

' ########## Information ##########
interface Information
abstract class AbstractInformation {
    - BigDecimal worth
}
class KnowHow {
    - int providerID
}
class ICTInformation
enum AgricultureInformationType {
    KNOW_HOW
    ICT_INFORMATION
}

AbstractInformation ..|> Information
KnowHow --|> AbstractInformation
ICTInformation --|> AbstractInformation
KnowHow ..|> Information
ICTInformation .l.|> Information

' ########## Server ##########
class AISServer << (S,#FF7700) Singleton >>{
    -{static} AISServer instance
    - List<ServerAgent> agricultureInformationAgents
    +{static} AISServer getInstance()
    + ServerAgent getAgricultureInformationAgent(String)
    + ServerAgent newIncentiveNegotiationAgent()
    + ServerAgent newInformationNegotiationAgent()
}
interface ServerAgent
abstract class AbstractServerAgent
class IncentiveNegotiationAgent {
    + BigDecimal negotiate(Information, BigDecimal)
}
class AgricultureInformationAgent {
    - List<Information> agricultureInformation
    + boolean register(Information)
    + BigDecimal getInformationWorth(int)
}
class InformationNegotiationAgent

AbstractServerAgent ..|> ServerAgent
IncentiveNegotiationAgent --|> AbstractServerAgent
AgricultureInformationAgent --|> AbstractServerAgent
InformationNegotiationAgent --|> AbstractServerAgent
IncentiveNegotiationAgent ..|> ServerAgent
AgricultureInformationAgent ..|> ServerAgent
InformationNegotiationAgent ..|> ServerAgent
AISServer ..> IncentiveNegotiationAgent : <<create>>
AISServer ..> AgricultureInformationAgent : <<create>>
AISServer ..> InformationNegotiationAgent : <<create>>

Provider -- IncentiveNegotiationAgent

@enduml